apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ecommerce
data:
  ORDER_SERVICE_PORT: "8080"
  PAYMENT_SERVICE_PORT: "8081"
  PAYMENT_SERVICE_URL: "http://payment-service.ecommerce.svc.cluster.local:8081"
  DB_HOST: "postgres-service.ecommerce.svc.cluster.local"
  DB_PORT: "5432"
